### ISSUE TITLE
 HTTP Error 500 when script is run for the first time

### ISSUE THREAD

**Issue by Jan-Marcek** [OpenDataNode/ckanext-odn-ic2pc-sync#1]
When I run command for the first time. 
internalcatalog

```
root@debian:~# /usr/share/python/odn-ckan-shared/bin/paster --plugin=ckanext-odn-ic2pc-sync odn_ic2pc_sync_cmd run  --config=/etc/odn-simple/odn-ckan-ic/production.ini
2015-02-10 05:46:53,787 INFO  [ckanext] Starting [PublishingCmd run]
2015-02-10 05:46:53,791 INFO  [ckanext] pushing datasets from http://localhost/internalcatalog to http://localhost
2015-02-10 05:46:53,805 INFO  [ckanext] number of datasets: 1
2015-02-10 05:46:53,805 INFO  [ckanext] [1 / 1] processing dataset_obj with id/name (source ckan) test
2015-02-10 05:46:54,176 ERROR [ckanext] HTTP Error 500: Internal Server Error
2015-02-10 05:46:54,176 INFO  [ckanext] End of [PublishingCmd run]
root@debian:~# /usr/share/python/odn-ckan-shared/bin/paster --plugin=ckanext-odn-ic2pc-sync odn_ic2pc_sync_cmd run  --config=/etc/odn-simple/odn-ckan-ic/production.ini
2015-02-10 05:47:41,157 INFO  [ckanext] Starting [PublishingCmd run]
2015-02-10 05:47:41,161 INFO  [ckanext] pushing datasets from http://localhost/internalcatalog to http://localhost
2015-02-10 05:47:41,175 INFO  [ckanext] number of datasets: 1
2015-02-10 05:47:41,175 INFO  [ckanext] [1 / 1] processing dataset_obj with id/name (source ckan) test
2015-02-10 05:47:41,585 INFO  [ckanext] [1 / 1] dataset_obj test created OK
2015-02-10 05:47:41,585 INFO  [ckanext] creating / updating resource: name=sk-codelist-5202/sk-codelist-5202.zip
2015-02-10 05:47:41,885 INFO  [ckanext] deleting resources with names not in [u'sk-codelist-5202/sk-codelist-5202.zip']
2015-02-10 05:47:41,914 INFO  [ckanext] End of [PublishingCmd run]

```

publiccatalog

```
[Fri Feb 13 10:21:20 2015] [error] 2015-02-13 10:21:20,807 INFO  [ckan.lib.base]  /api/action/package_search render time 0.006 seconds
[Fri Feb 13 10:21:20 2015] [error] 2015-02-13 10:21:20,820 INFO  [ckan.lib.base]  /api/3/action/organization_show render time 0.005 seconds
[Fri Feb 13 10:21:21 2015] [error] 2015-02-13 10:21:21,050 INFO  [ckan.lib.base]  /api/action/organization_create render time 0.223 seconds
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] Error - <class 'sqlalchemy.exc.ProgrammingError'>: (ProgrammingError) operator does not exist: text = text[]
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] LINE 3: WHERE "group".id = ARRAY['d13ccc0f-3b59-4aee-b2d8-f3e0d1d1a4...
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]                          ^
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]  'SELECT "group".id AS group_id, "group".name AS group_name, "group".title AS group_title, "group".type AS group_type, "group".description AS group_description, "group".image_url AS g
roup_image_url, "group".created AS group_created, "group".is_organization AS group_is_organization, "group".approval_status AS group_approval_status, "group".state AS group_state, "group".revision_id AS group_revision_id \\nFROM "group"
\\nWHERE "group".id = %(id_1)s \\n LIMIT %(param_1)s' {'id_1': [u'd13ccc0f-3b59-4aee-b2d8-f3e0d1d1a481'], 'param_1': 1}
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] URL: http://localhost/api/action/package_create
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/weberror/errormiddleware.py', line 162 in __call__
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   app_iter = self.application(environ, sr_checker)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   resp = self.call_func(req, *args, **self.kwargs)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   return self.func(req, *args, **kwargs)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/fanstatic/publisher.py', line 234 in __call__
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   return request.get_response(self.app)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   application, catch_exc_info=False)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   app_iter = application(self.environ, start_response)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/webob/dec.py', line 147 in __call__
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   resp = self.call_func(req, *args, **self.kwargs)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/webob/dec.py', line 208 in call_func
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   return self.func(req, *args, **kwargs)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/fanstatic/injector.py', line 54 in __call__
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   response = request.get_response(self.app)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/webob/request.py', line 1053 in get_response
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   application, catch_exc_info=False)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/webob/request.py', line 1022 in call_application
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   app_iter = application(self.environ, start_response)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/beaker/middleware.py', line 73 in __call__
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   return self.app(environ, start_response)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/beaker/middleware.py', line 155 in __call__
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   return self.wrap_app(environ, session_start_response)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/routes/middleware.py', line 131 in __call__
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   response = self.app(environ, start_response)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/pylons/wsgiapp.py', line 125 in __call__
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   response = self.dispatch(controller, environ, start_response)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/pylons/wsgiapp.py', line 324 in dispatch
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   return controller(environ, start_response)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckan/controllers/api.py', line 70 in __call__
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   return base.BaseController.__call__(self, environ, start_response)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckan/lib/base.py', line 346 in __call__
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   res = WSGIController.__call__(self, environ, start_response)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/pylons/controllers/core.py', line 221 in __call__
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   response = self._dispatch_call()
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/pylons/controllers/core.py', line 172 in _dispatch_call
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   response = self._inspect_call(func)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/pylons/controllers/core.py', line 107 in _inspect_call
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   result = self._perform_call(func, args)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/pylons/controllers/core.py', line 60 in _perform_call
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   return func(**args)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckan/controllers/api.py', line 189 in action
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   result = function(context, request_data)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckan/logic/__init__.py', line 419 in wrapped
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   result = _action(context, data_dict, **kw)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckan/logic/action/create.py', line 144 in package_create
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   data, errors = _validate(data_dict, schema, context)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckan/lib/navl/dictization_functions.py', line 234 in validate
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   converted_data, errors = _validate(flattened, schema, context)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckan/lib/navl/dictization_functions.py', line 295 in _validate
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   convert(converter, key, converted_data, errors, context)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckan/lib/navl/dictization_functions.py', line 192 in convert
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   converter(key, converted_data, errors, context)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckan/logic/validators.py', line 44 in owner_org_validator
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   group = model.Group.get(value)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/ckan/model/group.py', line 144 in get
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   group = query.first()
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 2156 in first
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   ret = list(self[0:1])
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 2023 in __getitem__
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   return list(res)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 2227 in __iter__
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   return self._execute_and_instances(context)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/sqlalchemy/orm/query.py', line 2242 in _execute_and_instances
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   result = conn.execute(querycontext.statement, self._params)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/sqlalchemy/engine/base.py', line 1449 in execute
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   params)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/sqlalchemy/engine/base.py', line 1584 in _execute_clauseelement
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   compiled_sql, distilled_params
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/sqlalchemy/engine/base.py', line 1698 in _execute_context
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   context)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/sqlalchemy/engine/base.py', line 1691 in _execute_context
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   context)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] File '/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/sqlalchemy/engine/default.py', line 331 in do_execute
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   cursor.execute(statement, parameters)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] ProgrammingError: (ProgrammingError) operator does not exist: text = text[]
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] LINE 3: WHERE "group".id = ARRAY['d13ccc0f-3b59-4aee-b2d8-f3e0d1d1a4...
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]                          ^
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]  'SELECT "group".id AS group_id, "group".name AS group_name, "group".title AS group_title, "group".type AS group_type, "group".description AS group_description, "group".image_url AS group_image_url, "group".created AS group_created, "group".is_organization AS group_is_organization, "group".approval_status AS group_approval_status, "group".state AS group_state, "group".revision_id AS group_revision_id \\nFROM "group" \\nWHERE "group".id = %(id_1)s \\n LIMIT %(param_1)s' {'id_1': [u'd13ccc0f-3b59-4aee-b2d8-f3e0d1d1a481'], 'param_1': 1}
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] CGI Variables
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] -------------
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   CKAN_CURRENT_URL: '/api/action/package_create'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   CKAN_LANG: 'en'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   CKAN_LANG_IS_DEFAULT: True
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   CONTENT_TYPE: 'application/x-www-form-urlencoded; charset=utf-8'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   DOCUMENT_ROOT: '/var/www'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   GATEWAY_INTERFACE: 'CGI/1.1'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   HTTP_ACCEPT_ENCODING: 'identity'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   HTTP_AUTHORIZATION: '3c49fb11-4b9c-49b2-9590-b25d8a398644'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   HTTP_CONNECTION: 'Keep-Alive'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   HTTP_HOST: 'localhost'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   HTTP_USER_AGENT: 'Python-urllib/2.7'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   HTTP_X_FORWARDED_FOR: '127.0.0.1'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   HTTP_X_FORWARDED_HOST: 'localhost'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   HTTP_X_FORWARDED_SERVER: 'odn'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   PATH_INFO: '/api/action/package_create'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   PATH_TRANSLATED: '/etc/odn-simple/odn-ckan-pc/apache.wsgi/api/action/package_create'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   REMOTE_ADDR: '127.0.0.1'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   REMOTE_PORT: '44893'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   REQUEST_METHOD: 'POST'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   REQUEST_URI: '/api/action/package_create'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   SCRIPT_FILENAME: '/etc/odn-simple/odn-ckan-pc/apache.wsgi'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   SERVER_ADDR: '127.0.0.1'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   SERVER_ADMIN: '[no address given]'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   SERVER_NAME: 'localhost'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   SERVER_PORT: '80'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   SERVER_PROTOCOL: 'HTTP/1.1'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   SERVER_SIGNATURE: '<address>Apache/2.2.22 (Debian) Server at localhost Port 80</address>\\n'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   SERVER_SOFTWARE: 'Apache/2.2.22 (Debian)'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] WSGI Variables
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] --------------
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   application: <fanstatic.publisher.Delegator object at 0x7f4245309690>
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   beaker.cache: <beaker.cache.CacheManager object at 0x7f42453099d0>
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   beaker.get_session: <bound method SessionMiddleware._get_session of <beaker.middleware.SessionMiddleware object at 0x7f4245309650>>
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   beaker.session: {'_accessed_time': 1423819281.068646, '_creation_time': 1423819281.068646}
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   fanstatic.needed: <fanstatic.core.NeededResources object at 0x7f42470c51d0>
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   mod_wsgi.application_group: 'odn-ckan-pc.example.org|'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   mod_wsgi.callable_object: 'application'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   mod_wsgi.handler_script: ''
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   mod_wsgi.input_chunked: '0'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   mod_wsgi.listener_host: ''
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   mod_wsgi.listener_port: '9090'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   mod_wsgi.process_group: 'odn-ckan-pc'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   mod_wsgi.request_handler: 'wsgi-script'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   mod_wsgi.script_reloading: '1'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   mod_wsgi.version: (3, 3)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   paste.cookies: (<SimpleCookie: >, '')
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   paste.registry: <paste.registry.Registry object at 0x7f42470c5790>
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   paste.throw_errors: True
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   pylons.action_method: <bound method ApiController.action of <ckan.controllers.api.ApiController object at 0x7f42470c0c50>>
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   pylons.controller: <ckan.controllers.api.ApiController object at 0x7f42470c0c50>
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   pylons.environ_config: {'session': 'beaker.session', 'cache': 'beaker.cache'}
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   pylons.pylons: <pylons.util.PylonsContext object at 0x7f42470c05d0>
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   pylons.routes_dict: {'action': u'action', 'controller': u'api', 'ver': 3, 'logic_function': u'package_create'}
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   pylons.status_code_redirect: True
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   repoze.who.logger: <logging.Logger object at 0x7f42452f82d0>
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   repoze.who.plugins: {'openid': <OpenIdIdentificationPlugin 139922605380304>, 'friendlyform': <FriendlyFormPlugin 139922605381584>, 'ckan.lib.authenticator:UsernamePasswordAuthenticator': <ckan.lib.authenticator.UsernamePasswordAuthenticator object at 0x7f4245ad6e90>, 'auth_tkt': <AuthTktCookiePlugin 139922605380368>, 'ckan.lib.authenticator:OpenIDAuthenticator': <ckan.lib.authenticator.OpenIDAuthenticator object at 0x7f4245ad6e50>}
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   routes.route: <routes.route.Route object at 0x7f424564bb90>
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   routes.url: <routes.util.URLGenerator object at 0x7f42470e9f90>
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   webob._parsed_post_vars: (MultiDict([('{"extras": [{"state": "active", "value": "https://www.dropbox.com/s/llhe69a0xub8bzg/foaf.rdf?dl=0", "revision_timestamp": "2015-01-22T09:53:39.477454", "package_id": "9e4b3439-a2d3-4326-909b-37c8cb792f9c", "key": "creator", "revision_id": "211bc2fb-2d05-4cba-862f-b61522ce05e2", "id": "d02a66a9-fa1e-45a7-a4e9-d4698dcae183"}, {"state": "active", "value": "http://comsode.eu/resource/dataset/IT_X_16", "revision_timestamp": "2015-01-22T09:53:39.477454", "package_id": "9e4b3439-a2d3-4326-909b-37c8cb792f9c", "key": "dataset", "revision_id": "211bc2fb-2d05-4cba-862f-b61522ce05e2", "id": "084029bb-d783-4399-af10-bdc53215b2c1"}, {"state": "active", "value": "http://opendefinition.org/licenses/cc-by/", "revision_timestamp": "2015-01-22T09:53:39.477454", "package_id": "9e4b3439-a2d3-4326-909b-37c8cb792f9c", "key": "license", "revision_id": "211bc2fb-2d05-4cba-862f-b61522ce05e2", "id": "2bbfe732-21e3-4924-8a32-63f1b88117dd"}, {"state": "active", "value": "2014-11-2...t([('{"...'')])>)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   webob._parsed_query_vars: (GET([]), '')
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   webob.adhoc_attrs: {'errors': 'ignore', 'response': <Response at 0x7f42470c66d0 200 OK>, 'language': 'en-us'}
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   webob.is_body_readable: True
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   webob.is_body_seekable: False
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   wsgi process: 'Multi process AND threads (?)'
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   wsgi.file_wrapper: <built-in method file_wrapper of mod_wsgi.Adapter object at 0x7f42471bceb8>
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   wsgi.version: (1, 1)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   wsgiorg.routing_args: (<routes.util.URLGenerator object at 0x7f42470e9f90>, {'action': u'action', 'controller': u'api', 'ver': 3, 'logic_function': u'package_create'})
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] ------------------------------------------------------------
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]             <p>Additionally an error occurred while sending the &lt;weberror.reporter.EmailReporter object at 0x7f4246f05810&gt; report:
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]             <pre>Traceback (most recent call last):
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   File "/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/weberror/errormiddleware.py", line 450, in send_report
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]     rep.report(exc_data)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   File "/usr/share/python/odn-ckan-shared/lib/python2.7/site-packages/weberror/reporter.py", line 45, in report
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]     server = smtplib.SMTP(self.smtp_server)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   File "/usr/lib/python2.7/smtplib.py", line 249, in __init__
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]     (code, msg) = self.connect(host, port)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   File "/usr/lib/python2.7/smtplib.py", line 309, in connect
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]     self.sock = self._get_socket(host, port, self.timeout)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   File "/usr/lib/python2.7/smtplib.py", line 284, in _get_socket
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]     return socket.create_connection((port, host), timeout)
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]   File "/usr/lib/python2.7/socket.py", line 571, in create_connection
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]     raise err
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] error: [Errno 111] Connection refused
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1] </pre>
[Fri Feb 13 10:21:21 2015] [error] [client 127.0.0.1]             </p>
[Fri Feb 13 10:21:23 2015] [error] 2015-02-13 10:21:23,643 INFO  [ckan.lib.base]  /user/admin render time 0.229 seconds


```

**Comment by Jan-Marcek** [comment]
fixed by https://github.com/OpenDataNode/ckanext-odn-ic2pc-sync/commit/8ad802ddb22cbdf54b8398d4dd6bf876f326edf1
